name: test ESlint

on:
  push:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: make install
      - name: tests
        run: make test
