name: tests

on:
  push:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          id_codeclimate: ${{ secrets.ID_CODECLIMATE }}
      - name: install
        run: make install
      - name: tests
        run: make test
